# Generated by Django 5.0 on 2024-01-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_alter_message_togroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('time_send',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timeSend',
            new_name='time_send',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='toGroup',
            new_name='to_group',
        ),
    ]
