# Generated by Django 5.0 on 2024-01-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.CharField(default='avt.jpg', max_length=200),
        ),
    ]
