# Generated by Django 5.0 on 2024-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(default='avt.jpg', upload_to='static/images/'),
        ),
    ]
